Hofre/Hofre/Areas/Admin/Pages/Users/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using UM.Application.Contract.User;
using UM.Application.Contract.UserRole;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Users
{
    public class CreateModel : PageModel
    {
        private readonly IUserApplication _repository;
        private readonly IUserRoleApplication _role;
        public List<SelectListItem> roles;
        public CreateModel(IUserApplication repository, IUserRoleApplication role)
        {
            _repository = repository;
            _role = role;
        }

        public  async void OnGet()
        {
            var GetRoles = (await _role.GetAll()).Select(x => new SelectListItem(x.RoleName, x.Id.ToString())).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(CreateUser commend)
        {
            await _repository.Create(commend);
            return RedirectToPage("./index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Users/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;
using UM.Application.Contract.User;
using UM.Application.Contract.UserRole;

namespace Hofre.Areas.Admin.Pages.Users
{
    public class IndexModel : PageModel
    {
        private readonly IUserApplication _repository;
        public List<UserViewModel> Users { get; set; }
        public IndexModel(IUserApplication repository)
        {
            _repository = repository;
        }

        public async Task OnGet()
        {
            Users = await _repository.GetAll();   
        }
        public async Task<RedirectToPageResult> OnPostRemove(long Id)
        {
            await _repository.Remove(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostActive(long Id)
        {
            await _repository.Active(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostDeActive(long Id)
        {
            await _repository.DeActive(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> ChangePassword(long Id,string newPassword)
        {
            await _repository.ChangePassword(Id, newPassword);
            return RedirectToPage();
        }

    }
}

Hofre/Hofre/Areas/Admin/Pages/Users/UserRoles/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;
using UM.Application.Contract.UserRole;

namespace Hofre.Areas.Admin.Pages.Users.UserRoles
{
    public class IndexModel : PageModel
    {
        private readonly IUserRoleApplication _repository;
        public List<UserRoleViewModel> UserRoles { get; set; }
        
       
        public IndexModel(IUserRoleApplication repository)
        {
            _repository = repository;
        }

        public async Task OnGet()
        {
            UserRoles = await _repository.GetAll();
            

        }
        public async Task OnPost(CreateUserRole commend)
        {
            await _repository.Create(commend);
        }
        public async Task<RedirectToPageResult> OnPostPermission(List<string> Permissions,long RoleId)
        {
            await _repository.AddPermissions(Permissions, RoleId);
            return RedirectToPage();
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Users/UserRoles/Index.cshtml
@page
@model Hofre.Areas.Admin.Pages.Users.UserRoles.IndexModel
@{
}


<div class="content-body">
    <!-- Page Headings Start -->
    <div class="row justify-content-between align-items-center mb-10">


        <!-- Page Heading Start -->
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3 class="title">دسته بندی دوره ها</h3>
            </div>

        </div><!-- Page Heading End -->
      
    </div><!-- Page Headings End -->

    <div class="row">
        <!--Modal Edit-->
        <div class="modal fade" id="exampleModal5">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">پیام جدید</h5>
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-page-handler="Permission">
                            <div class="form-group">
                                <select class="form-control" name="Permissions" multiple>
                                    <optgroup label="مقالات" style="text-align:center;background-color:lightblue;"></optgroup>
                                    <option value="Permission.Article.Create">ایجاد</option>
                                    <option value="Permission.Article.View">مشاهده</option>
                                    <option value="Permission.Article.Edit">ویرایش</option>
                                    <option value="Permission.Article.Delete">حذف</option>
                                    <optgroup label="دوره ها" style="text-align:center;background-color:lightblue;"></optgroup>
                                    <option value="Permission.Course.Create">ایجاد</option>
                                    <option value="Permission.Course.View">مشاهده</option>
                                    <option value="Permission.Course.Edit">ویرایش</option>
                                    <option value="Permission.Course.Delete">حذف</option>
                                    <optgroup label="کاربران" style="text-align:center;background-color:lightblue;"></optgroup>
                                    <option value="Permission.User.Create">ایجاد</option>
                                    <option value="Permission.User.View">مشاهده</option>
                                    <option value="Permission.User.Edit">ویرایش</option>
                                    <option value="Permission.User.Delete">حذف</option>
                                    <optgroup label="تنظیمات" style="text-align:center;background-color:lightblue;"></optgroup>
                                    <option value="Permission.Setting.Create">ویرایش</option>
                                    <optgroup label="تخفیفات" style="text-align:center;background-color:lightblue;"></optgroup>
                                    <option value="Permission.Discount.Create">ایجاد</option>
                                    <option value="Permission.Discount.View">مشاهده</option>
                                    <option value="Permission.Discount.Edit">ویرایش</option>
                                    <option value="Permission.Discount.Delete">حذف</option>
                                </select>
                                <input type="hidden" class="form-control" name="RoleId" id="UserRoleId">
                            </div>
                            <div class="modal-footer">
                                <button class="button button-danger" data-dismiss="modal">بستن</button>
                                <button type="submit" class="button button-primary">اعمال</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>


        <!--Basic Start-->
        <div class="col-12 mb-30">

            <div class="box">
                <div class="box-head">
                    <h3 class="title">لیست</h3>
                </div>
                <div class="box-body">

                    <table class="table footable" data-paging="true" data-filtering="true" data-sorting="true" data-breakpoints='{ "xs": 480, "sm": 768, "md": 992, "lg": 1200, "xl": 1400 }'>

                        <thead>
                            <tr>
                                <th data-name="نام دسترسی">نام دسترسی</th>
                                <th>سطح دسترسی ها</th>

                            </tr>
                        </thead>

                        <tbody>

                            @foreach (var item in Model.UserRoles)
                            {
                                <tr>

                                    <td>@item.RoleName</td>


                                    <td>
                                        <button class="button button-disqus" data-toggle="modal" data-target="#exampleModal5" data-whatever="mdo" onclick="RoleId(@item.Id)">مدیریت</button>
                                    </td>
                                   
                                  
                                </tr>
                            }


                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
</div>

@section Scripts{
<!-- Global Vendor, plugins & Activation JS -->
<script src="~/assets/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="~/assets/js/vendor/jquery-3.3.1.min.js"></script>
<script src="~/assets/js/vendor/popper.min.js"></script>
<script src="~/assets/js/vendor/bootstrap.min.js"></script>
<!--Plugins JS-->
<script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="~/assets/js/plugins/tippy4.min.js.js"></script>
<!--Main JS-->
<script src="assets/js/main.js"></script>

<!-- Plugins & Activation JS For Only This Page -->
<script src="~/assets/js/plugins/moment/moment.min.js"></script>
<script src="~/assets/js/plugins/footable/footable.min.js"></script>
<script src="~/assets/js/plugins/footable/footable.active.js"></script>
}
<script>

    function RoleId(roleId){
        $("#UserRoleId").val(roleId)
    }
</script>