Hofre/Hofre/ViewComponents/ArticleCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Query.Modules.Article;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Hofre.ViewComponents
{
    public class ArticleCategoryViewComponent : ViewComponent
    {
        private readonly IArticleQueryRepository _repository;
        public ArticleCategoryViewComponent(IArticleQueryRepository repository)
        {
            _repository = repository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _repository.GetAllCategories();
            return View(categories);
        }
    }
}

Hofre/Hofre/ViewComponents/CourseCategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Query.Modules.Course;
using System.Threading.Tasks;

namespace Hofre.ViewComponents
{
    public class CourseCategoryViewComponent : ViewComponent
    {
        private readonly ICourseQueryRepository _repository;
        public CourseCategoryViewComponent(ICourseQueryRepository repository)
        {
            _repository = repository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var category = await _repository.GetAllCategories();
            return View(category);
        }
    }
}

Hofre/Hofre/Pages/Shared/_Layout.cshtml
@inject Frameworks.Auth.IAuth auth;


<!DOCTYPE html>

<html lang="fa">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="HTML5,CSS3,HTML,Template,multi-page,Zelda - eSports & Gaming Template">
    <meta name="description" content="Zelda - eSports & Gaming Template">
    <meta name="author" content="Barat Hadian">

    <!-- Links of CSS files -->
    <link rel="stylesheet" href="~/MainTheme/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/animate.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/boxicons.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/meanmenu.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/flaticon.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/fancybox.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/magnific-popup.min.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/style.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/responsive.css">
    <link rel="stylesheet" href="~/MainTheme/assets/css/rtl.css">

    <title>حفره</title>

    <link rel="icon" type="image/png" href="~/MainTheme/assets/img/favicon.png">
</head>

<body class="skin-dark">

    <!-- Start Navbar Area -->
    <div class="navbar-area">
        <div class="zelda-responsive-nav">
            <div class="container">
                <div class="zelda-responsive-menu">
                    <div class="logo">
                        <a href="index.html">
                            <img src="~/MainTheme/assets/img/logo.png" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="zelda-nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md navbar-light">
                    <a class="navbar-brand" href="index.html">
                        <img src="~/MainTheme/assets/img/logo.png" alt="logo">
                    </a>

                    <div class="collapse navbar-collapse mean-menu">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a asp-page="/index">خانه</a>
                            </li>
                            <li class="nav-item">
                                @if (await (auth.IsAuthenticated()))
                                {
                                    <a asp-page="/account" class="nav-link">حساب من</a>

                                }
                                else
                                {
                                    <a asp-page="/account" class="nav-link">ورود|ثبت نام</a>

                                }

                            </li>

                            <!--ArticleCategories-->
                            @(await Component.InvokeAsync("ArticleCategory"))
                            <!--CourseCategories-->
                            @(await Component.InvokeAsync("CourseCategory"))

                            <li class="nav-item"><a href="contact.html" class="nav-link">درباره ما</a></li>

                            <li class="nav-item"><a href="contact.html" class="nav-link">تماس با ما</a></li>
                        </ul>

                        <div class="others-option d-flex align-items-center">
                            <div class="option-item">
                                <div class="search-box">
                                    <i class="flaticon-search-1"></i>
                                </div>
                            </div>

                           
                        </div>
                    </div>
                </nav>
            </div>
        </div>

        <div class="others-option-for-responsive">
            <div class="container">
           

                <div class="container">
                    <div class="option-inner">
                        <div class="others-option">
                            <div class="option-item">
                                <div class="search-box">
                                    <i class="flaticon-search-1"></i>
                                </div>
                            </div>

                            <div class="option-item">
                                <div class="side-menu-btn">
                                    <i class="flaticon-null-2" data-toggle="modal" data-target="#sidebarModal"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Navbar Area -->
    <!-- Sidebar Modal -->
    <div class="sidebarModal modal right fade" id="sidebarModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal"><i class='bx bx-x'></i></button>

                <div class="modal-body">
                    <div class="logo">
                        <a href="index.html" class="d-inline-block"><img src="~/MainThemeassets/img/logo.png" alt="image"></a>
                    </div>

                    <div class="instagram-list">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainThemeassets/img/team-member1.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainThemeassets/img/team-member2.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainTheme/assets/img/team-member3.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainTheme/assets/img/team-member4.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainTheme/assets/img/team-member5.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-4 col-sm-4 col-6">
                                <div class="box">
                                    <img src="~/MainTheme/assets/img/team-member6.jpg" alt="image">
                                    <i class='bx bxl-instagram'></i>
                                    <a href="#" target="_blank" class="link-btn"></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="sidebar-contact-info">
                        <h2>
                            <a href="tel:+8802419268615">021-12345678</a>
                            <span>یا</span>
                            <a href="mailto:hello@zelda.com">hello@zelda.com</a>
                        </h2>
                    </div>

                    <ul class="social-list">
                        <li><span>ما را دنبال کنید:</span></li>
                        <li><a href="#" target="_blank"><i class='bx bxl-facebook'></i></a></li>
                        <li><a href="#" target="_blank"><i class='bx bxl-twitter'></i></a></li>
                        <li><a href="#" target="_blank"><i class='bx bxl-youtube'></i></a></li>
                        <li><a href="#" target="_blank"><i class='bx bxl-twitch'></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Sidebar Modal -->
    <!-- Search Overlay -->
    <div class="search-overlay">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="search-overlay-layer"></div>
                <div class="search-overlay-layer"></div>
                <div class="search-overlay-layer"></div>

                <div class="search-overlay-close">
                    <span class="search-overlay-close-line"></span>
                    <span class="search-overlay-close-line"></span>
                </div>

                <div class="search-overlay-form">
                    <form asp-page="/Search" method="get">
                        <input type="text" name="entery" class="input-search" placeholder="جستجو ..." />
                        <button type="submit"><i class="flaticon-search-1"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- End Search Overlay -->
    <!-- Start Page Title Area -->
    <!-- End Page Title Area -->
    <!-- Start Blog Area -->
    @RenderBody();
    <!-- End Blog Area -->
    <!-- Start Footer Area -->
    <footer class="footer-area bg-1b060a ptb-70">
        <div class="container">
            <div class="footer-content">
                <div class="logo">
                    <a href="#" class="d-inline-block"><img src="~/MainTheme/assets/img/logo.png" alt="image"></a>
                    <ul class="footer-menu">
                        <li class="nav-item"><a class="nav-link" href="#">درباره ما</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">پشتیبانی</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">حساب کاربری</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <div class="copyright-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-sm-5">
                    <p>کپی رایت 1399 <i class='bx bx-copyright'></i>  تمام حقوق قالب محفوظ است. توسعه توسط علی طاهری</p>
                </div>


            </div>
        </div>
    </div>
    <!-- End Footer Area -->

    <div class="go-top"><i class='bx bx-up-arrow-alt'></i></div>

    <div class="zelda-cursor"></div>
    <div class="zelda-cursor2"></div>


    <!-- Links of JS files -->
    <script src="~/MainTheme/assets/js/jquery.min.js"></script>
    <script src="~/MainTheme/assets/js/popper.min.js"></script>
    <script src="~/MainTheme/assets/js/bootstrap.min.js"></script>
    <script src="~/MainTheme/assets/js/owl.carousel.min.js"></script>
    <script src="~/MainTheme/assets/js/magnific-popup.min.js"></script>
    <script src="~/MainTheme/assets/js/parallax.min.js"></script>
    <script src="~/MainTheme/assets/js/meanmenu.min.js"></script>
    <script src="~/MainTheme/assets/js/isotope.pkgd.min.js"></script>
    <script src="~/MainTheme/assets/js/cursor.min.js"></script>
    <script src="~/MainTheme/assets/js/fancybox.min.js"></script>
    <script src="~/MainTheme/assets/js/wow.min.js"></script>
    <script src="~/MainTheme/assets/js/form-validator.min.js"></script>
    <script src="~/MainTheme/assets/js/contact-form-script.js"></script>
    <script src="~/MainTheme/assets/js/ajaxchimp.min.js"></script>
    <script src="~/MainTheme/assets/js/main.js"></script>
</body>
</html>