Hofre/Hofre/Areas/Admin/Pages/ArticleCategories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hofre.Areas.Admin.Pages.ArticleCategories
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _repository;

        public CreateModel(IArticleCategoryApplication repository)
        {
            _repository = repository;
        }

        public void OnGet()
        {
        }
        public async Task<RedirectToPageResult> OnPost(CreateArticleCategory commend)
        {
           await _repository.Create(commend);
            return RedirectToPage("./Index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/ArticleCategories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hofre.Areas.Admin.Pages.ArticleCategories
{
    public class EditModel : PageModel
    {
        private readonly IArticleCategoryApplication _repository;
        [BindProperty] public EditArticleCategory articleCategory { get; set; }
        public EditModel(IArticleCategoryApplication repository)
        {
            _repository = repository;
        }

        public async Task OnGet(long Id)
        {
            articleCategory =await _repository.GetValueForEdit(Id);
        }
        public async Task<RedirectToPageResult> OnPost(EditArticleCategory commend)
        {
            await _repository.Edit(commend);

            return RedirectToPage("./Index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Articles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM.Application.Contract.Article;
using AM.Application.Contract.ArticleCategory;
using Frameworks.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Hofre.Areas.Admin.Pages.Articles
{
    [Authorize(Policy = PermissionTypes.Article.Create)]
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articlecategory;
        public List<SelectListItem> categories;
        private readonly IArticleApplication _repository;
        public CreateModel(IArticleCategoryApplication articlecategory, IArticleApplication repository)
        {
            _articlecategory = articlecategory;
            _repository = repository;
        }

        public async Task OnGet()
        {
            categories = (await _articlecategory.GetAll()).Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();

        }
        public async Task<RedirectToPageResult> OnPost(CreateArticle commend)
        {
            await _repository.Create(commend);

            return RedirectToPage("./Index");
        }

    }
}

Hofre/Hofre/Areas/Admin/Pages/Articles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM.Application.Contract.Article;
using AM.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Hofre.Areas.Admin.Pages.Articles
{
    public class EditModel : PageModel
    {
        private readonly IArticleCategoryApplication _articlecategory;
        public List<SelectListItem> categories;
        private readonly IArticleApplication _repository;
        public List<SelectListItem> articleTags;
        public List<ArticleTagViewModel> tags;
        [BindProperty] public EditArticle Article { get; set; }

        public EditModel(IArticleCategoryApplication articlecategory, IArticleApplication repository)
        {
            _articlecategory = articlecategory;
            _repository = repository;
        }

        public async Task OnGet(long Id)
        {
            Article = await _repository.GetValueForEdit(Id);
            articleTags =(await _repository.GetTagsBy(Id)).Select(x=>new SelectListItem(x.Title,x.TagId.ToString())).ToList();
            tags = await _repository.GetTagsBy(Id);
            categories = (await _articlecategory.GetAll()).Select(x => new SelectListItem(x.Name, x.Id.ToString(), true)).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(EditArticle commend)
        {
            await _repository.Edit(commend);
            return RedirectToPage("./Index");
        }

    }
}

Hofre/Hofre/Areas/Admin/Pages/CourseCategories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CM.Application.Contract.CourseCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hofre.Areas.Admin.Pages.CourseCategories
{
    public class CreateModel : PageModel
    {
        private readonly ICourseCategoryApplication _repository;

        public CreateModel(ICourseCategoryApplication repository)
        {
            _repository = repository;
        }

        public void OnGet()
        {
        }
        public RedirectToPageResult OnPost(CreateCourseCategory commend)
        {
            _repository.Create(commend);
            return RedirectToPage("./index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/CourseCategories/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CM.Application.Contract.CourseCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hofre.Areas.Admin.Pages.CourseCategories
{
    public class EditModel : PageModel
    {
        private readonly ICourseCategoryApplication _repository;

        public EditModel(ICourseCategoryApplication repository)
        {
            _repository = repository;
        }

        [BindProperty] public EditCourseCategory courseCategory { get; set; }
        public async Task OnGet(long Id)
        {
            courseCategory = await _repository.GetValueForEdit(Id);
        }
        public async Task<RedirectToPageResult> OnPost(EditCourseCategory commend)
        {
           await _repository.Edit(commend);
            return RedirectToPage("./index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Courses/Comment.cshtml.cs
using CM.Application.Contract.CourseComment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Courses
{
    public class CommentModel : PageModel
    {
        private readonly ICourseCommentApplication _repository;
        public List<CourseCommentViewModel> Comments { get; set; }
        public CommentModel(ICourseCommentApplication repository)
        {
            _repository =  repository;
        }
        public async Task OnGet()
        {
            Comments = await _repository.GetAll();

        }
        public async Task<RedirectToPageResult> OnPostActive(long Id)
        {
            await _repository.Active(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostDeActive(long Id)
        {
            await _repository.DeActive(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostDelete(long Id)
        {
            await _repository.Remove(Id);
            return RedirectToPage();
        }

    }
}

Hofre/Hofre/Areas/Admin/Pages/Courses/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using CM.Application.Contract.Course;
using CM.Application.Contract.CourseCategory;
using Frameworks.Auth;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Hofre.Areas.Admin.Pages.Courses
{
    [Authorize(Policy =PermissionTypes.Course.Create)]
    public class CreateModel : PageModel
    {
        private readonly ICourseApplication _repository;
        private readonly ICourseCategoryApplication _category;
        public List<SelectListItem> categories;

        public CreateModel(ICourseApplication repository, ICourseCategoryApplication category)
        {
            _repository = repository;
            _category = category;
        }
      
        public async Task OnGet()
        {
           
            categories = (await _category.GetAll()).Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();

        }
        public async Task<RedirectToPageResult> OnPost(CreateCourse commend)
        {
           await _repository.Create(commend);
           
            return RedirectToPage("./index");   
        }
      
    }
}

Hofre/Hofre/Areas/Admin/Pages/Courses/Edit.cshtml.cs
using CM.Application.Contract.Course;
using CM.Application.Contract.CourseCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Courses
{
    public class EditModel : PageModel
    {
        private readonly ICourseApplication _repository;
        private readonly ICourseCategoryApplication _category;
        [BindProperty] public EditCourse course { get; set; }
        public List<SelectListItem> categories { get; set; }
      

        public EditModel(ICourseApplication repository, ICourseCategoryApplication category)
        {
            _repository = repository;
            _category = category;
        }

        public async Task OnGet(long Id)
        {
            course = await _repository.GetValueForEdit(Id);
            categories = (await _category.GetAll()).Select(x=> new SelectListItem(x.Name, x.Id.ToString())).ToList();

        }
        public async Task<RedirectToPageResult> OnPost(EditCourse edit)
        {
            await _repository.Edit(edit);
            return RedirectToPage("./Index");
        }
        public async Task<RedirectToPageResult> OnPostDeleteVideo(long Id,string folder)
        {
            await _repository.DeleteVideo(Id, folder);
            return RedirectToPage();
       }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Courses/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CM.Application.Contract.Course;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hofre.Areas.Admin.Pages.Courses
{
    public class IndexModel : PageModel
    {
        private readonly ICourseApplication _repository;
        public List<CourseViewModel> courses;
        public List<CourseVideos> videos { get; set; }
        public IndexModel(ICourseApplication repository)
        {
            _repository = repository;
        }

        public async Task OnGet()
        {
            courses = await _repository.GetAll();

        }
        public async Task<RedirectToPageResult> OnPostActive(long Id)
        {
           await _repository.Active(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostDeActive(long Id)
        {
           await _repository.DeActive(Id);
            return RedirectToPage();
        }
        public async Task<RedirectToPageResult> OnPostRemove(long Id)
        {
           await _repository.Remove(Id);
            return RedirectToPage();
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Discounts/Coupon/Create.cshtml.cs
using CM.Application.Contract.Course;
using DM.Application.Contract.DiscountCoupon;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Discounts.Coupon
{
    public class CreateModel : PageModel
    {
        private readonly ICouponApplication _repository;
        private readonly ICourseApplication _course;

        public CreateModel(ICouponApplication repository, ICourseApplication course)
        {
            _repository = repository;
            _course = course;
        }

        public List<SelectListItem> Courses { get; set; }
        public async Task OnGet()
        {
            Courses = (await _course.GetAll()).Select(x =>new SelectListItem(x.Subject,x.Id.ToString())).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(CreateCoupon commend)
        {
            await _repository.Create(commend);
            return RedirectToPage("./index");

        }

    }
}

Hofre/Hofre/Areas/Admin/Pages/Discounts/Coupon/Edit.cshtml.cs
using CM.Application.Contract.Course;
using DM.Application.Contract.DiscountCoupon;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Discounts.Coupon
{
    public class EditModel : PageModel
    {
        private readonly ICouponApplication _repository;
        private readonly ICourseApplication _course;

        public EditCoupon Coupon { get; set; }
        public List<SelectListItem> Courses { get; set; }
        public EditModel(ICouponApplication repository,ICourseApplication course)
        {
            _repository = repository;
            _course = course;
        }
        public async Task OnGet(long Id)
        {
            Coupon = await _repository.GetValueForEdit(Id);
            Courses = (await _course.GetAll()).Select(x => new SelectListItem(x.Subject, x.Id.ToString())).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(EditCoupon commend)
        {
            await _repository.Edit(commend);
            return RedirectToPage("./index");
        }
      
    }
}

Hofre/Hofre/Areas/Admin/Pages/Discounts/Create.cshtml.cs
using CM.Application.Contract.Course;
using DM.Application.Contract.CustomerDiscount;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Discounts
{
    public class CreateModel : PageModel
    {
        private readonly IDiscountApplication _repository;
        private readonly ICourseApplication _course;
        public List<SelectListItem> Courses;

        public CreateModel(IDiscountApplication repository, ICourseApplication course)
        {
            _repository = repository;
            _course = course;
        }

        public async Task OnGet()
        {
            Courses = (await _course.GetAll()).Select(x => new SelectListItem(x.Subject, x.Id.ToString())).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(CreateDiscount commend)
        {
            await _repository.Create(commend);
            return RedirectToPage("./Index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Users/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using UM.Application.Contract.User;
using UM.Application.Contract.UserRole;
using System.Linq;
using System.Threading.Tasks;

namespace Hofre.Areas.Admin.Pages.Users
{
    public class CreateModel : PageModel
    {
        private readonly IUserApplication _repository;
        private readonly IUserRoleApplication _role;
        public List<SelectListItem> roles;
        public CreateModel(IUserApplication repository, IUserRoleApplication role)
        {
            _repository = repository;
            _role = role;
        }

        public  async void OnGet()
        {
            var GetRoles = (await _role.GetAll()).Select(x => new SelectListItem(x.RoleName, x.Id.ToString())).ToList();
        }
        public async Task<RedirectToPageResult> OnPost(CreateUser commend)
        {
            await _repository.Create(commend);
            return RedirectToPage("./index");
        }
    }
}

Hofre/Hofre/Areas/Admin/Pages/Courses/Comment.cshtml
@page
@model Hofre.Areas.Admin.Pages.Courses.CommentModel
@{
}

<div class="content-body">

    <!-- Page Headings Start -->
    <div class="row justify-content-between align-items-center mb-10">

        <!-- Page Heading Start -->
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3> نظرات دوره ها</h3>
            </div>
        </div><!-- Page Heading End -->

    </div><!-- Page Headings End -->

    <div class="row">

        <!--Order List Start-->
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-vertical-middle">
                    <thead>
                        <tr>
                            <th>دوره</th>
                            <th>کاربر</th>
                            <th>متن</th>
                            <th>تاریخ</th>
                            <th>وضعیت</th>
                            <th>عملیات</th>
                            <th>حذف</th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @Model.Comments)
                        {
                            <tr>
                                <td>@item.CourseSubject</td>
                                <td>@item.Username</td>
                                <td>@item.Text</td>
                                <td>@item.CreationDate</td>
                                @if (item.IsActive)
                                {
                                    <td><span class="badge badge-success">تایید شده</span></td>
                                }
                                else
                                {
                                    <td><span class="badge badge-danger">در انتظار تایید</span></td>
                                }
                                <td class="action h4">
                                    <div class="table-action-buttons">

                                        @if (item.IsActive==false)
                                        {
                                            <form method="post" asp-page-handler="Active">
                                                <input name="Id" type="hidden" value="@item.Id">
                                                <button type="submit" class="edit button button-box button-xs button-primary"><i class="zmdi zmdi-more"></i></button>

                                            </form>
                                        }
                                        else
                                        {
                                            <form method="post" asp-page-handler="DeActive">
                                                <input name="Id" type="hidden" value="@item.Id">
                                                <button type="submit" class="edit button button-box button-xs button-danger"><i class="zmdi zmdi-more"></i></button>

                                            </form>
                                        }


                                    </div>
                                </td>
                                <td>
                                    <div class="table-action-buttons">

                                        <form method="post" asp-page-handler="Delete">
                                            <input type="hidden" name="Id" value="@item.Id">
                                            <button type="submit" class="delete button button-box button-xs button-danger"><i class="zmdi zmdi-delete"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
        <!--Order List End-->

    </div>
</div>

Hofre/Hofre/Areas/Admin/Pages/Courses/Index.cshtml
@page
@model Hofre.Areas.Admin.Pages.Courses.IndexModel
@{
}



<div class="content-body">
    <!-- Page Headings Start -->
    <div class="row justify-content-between align-items-center mb-10">


        <!-- Page Heading Start -->
        <div class="col-12 col-lg-auto mb-20">
            <div class="page-heading">
                <h3 class="title">دوره ها</h3>
            </div>

        </div><!-- Page Heading End -->
        <a class="button button-success" asp-page="./Create">افزودن دوره</a>
    </div><!-- Page Headings End -->

    <div class="row">


        <!--Basic Start-->
        <div class="col-12 mb-30">

            <div class="box">
                <div class="box-head">
                    <h3 class="title">لیست</h3>
                </div>
                <div class="box-body">

                    <table class="table footable" data-paging="true" data-filtering="true" data-sorting="true" data-breakpoints='{ "xs": 480, "sm": 768, "md": 992, "lg": 1200, "xl": 1400 }'>

                        <thead>
                            <tr>
                                <th data-name="تصویر">تصویر</th>
                                <th data-name="موضوع">موضوع</th>
                                <th data-name="دسته">دسته</th>
                                <th data-name="مدرس">مدرس</th>
                                <th data-name="قیمت دوره">قیمت دوره</th>
                                <th data-name="تاریخ شروع">تاریخ شروع</th>
                                <th data-name="تاریخ پایان">تاریخ پایان</th>
                                <th data-name="وضعیت">وضعیت</th>
                                <th>عملیات</th>
                                <th></th>

                            </tr>
                        </thead>

                        <tbody>


                            @foreach (var item in Model.courses)
                            {
                                <tr>

                                    <td height="50" width="80"><img src="~/Media/Course/@item.Subject/@item.Picture" /></td>
                                    <td>@item.Subject</td>
                                    <td>@item.CategoryName</td>
                                    <td>@item.Teacher</td>
                                    @if (item.IsFree == true)
                                    {
                                        <td>رایگان</td>
                                    }
                                    else
                                    {
                                        <td>@item.Price</td>

                                    }
                                    <td>@item.CreationDate</td>
                                    <td>@item.LastUpdate</td>
                                    @if (item.IsFinal == true)
                                    {
                                        <td>به اتمام رسیده</td>
                                    }
                                    else
                                    {
                                        <td>در حال ضبط</td>
                                    }
                                    <td width="70">
                                        <a class="button button-warning" asp-page="./Edit" asp-route-Id="@item.Id">ویرایش</a>
                                    </td>
                                    <td width="70">
                                        <form method="post" asp-page-handler="Remove">
                                            <input type="hidden" name="Id" value="@item.Id" />
                                            <button type="submit" class="button button-danger">حذف</button>
                                        </form>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>

</div><!-- Content Body End -->

<!--CourseVideo Modal-->





@section Scripts{
<!-- Global Vendor, plugins & Activation JS -->
<script src="~/assets/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="~/assets/js/vendor/jquery-3.3.1.min.js"></script>
<script src="~/assets/js/vendor/popper.min.js"></script>
<script src="~/assets/js/vendor/bootstrap.min.js"></script>
<!--Plugins JS-->
<script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="~/assets/js/plugins/tippy4.min.js.js"></script>
<!--Main JS-->
<script src="assets/js/main.js"></script>

<!-- Plugins & Activation JS For Only This Page -->
<script src="~/assets/js/plugins/moment/moment.min.js"></script>
<script src="~/assets/js/plugins/footable/footable.min.js"></script>
<script src="~/assets/js/plugins/footable/footable.active.js"></script>
}